# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
- xcodebuild clean build test -workspace Example/MYTableViewIndex.xcworkspace -scheme MYTableViewIndex-Example -destination 'platform=iOS Simulator,OS=10.3,name=iPhone 7' | xcpretty
- pod lib lint
